# Problem: Ugly Number II

# Pattern: Min-Heap (Generation).

# Why: Ugly numbers are generated by multiplying previous ugly numbers by 2, 3, or 5. We use a Min-Heap to always find the next smallest ugly number to multiply.

import heapq

def nthUglyNumber(n):
  minHeap = [1]
  visit = set([1])
  factors = [2, 3, 5]

  for _ in range(n - 1):
    num = heapq.heappop(minHeap)
    for f in factors:
      newNum = num * f
      if newNum not in visit:
        visit.add(newNum)
        heapq.heappush(minHeap, newNum)

  return heapq.heappop(minHeap)

# Complexity: Time O(N log N) | Space O(N)